local o = vim.opt
vim.g.mapleader = ' '       -- space is the leader key
o.expandtab = true          -- spaces, not tabs
o.shiftwidth = 2            -- 2 spaces per indent level
o.number = true             -- absolute number on the cursor line, relative elsewhere
o.relativenumber = true     -- relative line numbers for fast jumps
o.ignorecase = true         -- search is case-insensitive by default
o.smartcase = true          -- case-sensitive only if i type a capital
o.clipboard = 'unnamedplus' -- share the system clipboard
o.scrolloff = 16            -- keep cursor away from the screen edge
o.wrap = true               -- wrap long lines instead of scrolling sideways
o.linebreak = true          -- break at word boundaries, never mid-word
o.breakat = ' \t'            -- and only at whitespace, so aria-foo stays whole
o.breakindent = true        -- the wrapped part keeps the original indent
o.showbreak = '↳ '          -- glyph marking a wrapped continuation
o.breakindentopt = 'shift:-2' -- pull the wrap back left so the glyph hangs in the indent
o.smoothscroll = true       -- scroll by screen line, so wrapped lines don't jump wholesale
o.undofile = true           -- persistent undo across sessions
o.mouse = ''                -- no mouse in nvim; also lets Herdr keep host mouse capture off so Escape isn't swallowed
o.hlsearch = true
o.incsearch = true
